id: P009353
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC219
  title: 'དྲང་ངེས་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    f48967e771ef40e487c7559d66976ee4:
      image_group_id: I2PD18549
      title: ''
      volume_number: 1
      total_pages: 538
      base_file: v001.txt
